<?php
/**
 * Magify
 *
 * @category    template
 * @package     magify_ajaxlogin
 * @copyright   Copyright (c) 2012 Magify Inc. (http://www.magify.com)
 * @version		1.0
 * @author		Magify (info@magify.com)
 */
?>
<div class="page-title">
    <h1><?php echo Mage::helper('customer')->__('Forgot Your Password?') ?></h1>
</div>
<ul class="messages"></ul>
<form id="form-validate-retrievepwd">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('customer')->__('Retrieve your password here') ?></h2>
        <p><?php echo Mage::helper('customer')->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address" class="required"><em>*</em><?php echo Mage::helper('customer')->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set" style="margin-top:2em!important;">
        <p class="required">
			<?php echo Mage::helper('customer')->__('* Required Fields') ?>
		</p>
        <button type="button" onclick="mgretreivepassword()" title="<?php echo Mage::helper('customer')->__('Submit') ?>" class="button">
			<span><span><?php echo Mage::helper('customer')->__('Submit') ?></span></span>
		</button>
    </div>
</form>
<script type="text/javascript">
function mgretreivepassword()
{
	var dataForm = new VarienForm('form-validate-retrievepwd', true);
	if (!dataForm.validator.validate())
	{
		return;
	}
	
	jQuery.post(
	'<?php echo $this->getUrl("ajaxlogin/index/forgotpasswordpost"); ?>',
	jQuery('#form-validate-retrievepwd').serialize(),
	function(data) 
	{
		var result = eval("(" + data + ")");
		
		jQuery('#mg-forgotpassword-panel .messages').show();
		
		var msg = "";
		
		if (result.retrieved)
		{
			var msg = "<li class='success-msg'>" + result.detail + "</li>";
		}
		else
		{
			var msg = "<li class='error-msg'>" + result.detail + "</li>";
		}
				
		jQuery('#mg-forgotpassword-panel .messages').html(msg);
		jQuery.fancybox("#mg-forgotpassword-panel");
	});
}
</script>
