<?php
/**
 * Magify
 *
 * @category    template
 * @package     magify_ajaxlogin
 * @copyright   Copyright (c) 2012 Magify Inc. (http://www.magify.com)
 * @version		1.0
 * @author		Magify (info@magify.com)
 */
?>

<?php if(Mage::getStoreConfig('ajaxlogin/login/enabled')): ?>
	<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
	<div>
		<div class="login-panel" id="mg-login-panel" style="display: none">
			<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('ajaxlogin/login.phtml')->toHtml(); ?>		
		</div>
		<div id="mg-register-panel" style="display: none">
			<?php echo $this->getLayout()->createBlock('ajaxlogin/register')->setTemplate('ajaxlogin/register.phtml')->toHtml(); ?>		
		</div>	
		<div id="mg-forgotpassword-panel" style="display: none">
			<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('ajaxlogin/forgotpassword.phtml')->toHtml(); ?>
		</div>
	</div>
	
	<script type="text/javascript">
		jQuery(document).ready(function() {
			jQuery('header .links .first a').click(function(){
			
				jQuery('#mg-login-panel').fancybox({'type':'inline'});
				return false;
			});
		});
	</script>
	<?php endif; ?>
<?php endif; ?>