<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');

$_storeId = Mage::app()->getStore()->getId();
	if($_storeId == 1){
		$due = 'Due Today';
		$paid_curacao = 'Charge to Curacao account';
		$pu = 'Please use another form of payment ';
		$error_over_limit_1 = 'Your cart total exceeds your available Curacao credit of <strong>$</strong>';
		$error_over_limit_2 = ". Please adjust your cart or use an alternative payment method to pay the remaining balance to complete your purchase.";
		$error_dp = 'To complete your order, an initial payment is required. Please use an alternative payment method to pay the amount due today.';
	} else {
		$due = 'Pago Inicial Requerido';
		$paid_curacao = 'Cargar a la cuenta de Curacao';
		$pu = 'Por favor use otra forma de pago ';
		$error_over_limit_1 = 'El monto total en su carrito de compras excede el crédito disponible de <strong>$</strong>';
		$error_over_limit_2 = ' en su cuenta de Curacao. Por favor revise los productos en su carrito o utilice un método de pago alternativo para pagar el saldo restante y poder completar su compra.';
		$error_dp = 'Para completar su orden, se requiere un pago inicial. Por favor utilice un método de pago alternativo para pagar el monto requerido.';
	}

$Data = Mage::getSingleton('core/session')->getCuracacaodp();

$i = 0;
	
?>
<div id="summery_cart">
<table class="onestepcheckout-summary">
    <thead>
        <tr>
            <th class="name"><?php echo $this->__('Product'); ?></th>
            <th class="qty"><?php echo $this->__('Qty'); ?></th>
            <th class="total"><?php echo $this->__('Subtotal'); ?></th>
        </tr>
    </thead>
    
    <?php 
	
	foreach($this->getItems() as $item): ?>
    <?php $products .= ";".$_item->getSku()?>
    <tr>
        <td class="name">
            <?php echo $item->getName(); ?>
			<?php ?>	
            <?php if($checkoutHelper->settings['show_custom_options']): ?>
                <?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
                <?php if(isset($options['options']) && count($options['options']) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($options['options'] as $option): ?>
                    <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php if($item->getProduct()->isConfigurable()): ?>

                <?php
                $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
                ?>

                <?php if(is_array($configurable_options) && count($configurable_options) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($configurable_options as $option): ?>
                    <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php endif; ?>

            <?php endif; ?><br />
				<button class="update-button" title="Update Shopping Cart" value="update_qty" name="update_cart_action" type="submit" onclick="return removeItem('<?php echo $item->getProductId() ?>')">Remove</button>
        </td>
        <input type="hidden" name="productId" value="<?php echo $item->getProductId(); ?>" id="prId_<?php echo $i?>" />
        <td class="qty"><input name="cart[<?php echo $item->getId() ?>][qty]" value="<?php echo $item->getQty() ?>" size="1" title="<?php echo $this->__('Qty') ?>" id="prqty_<?php echo $item->getProductId()?>" class="input-text qty-box" maxlength="12" /><?php //echo $item->getQty(); ?><br />
	<button class="update-button" title="Update Shopping Cart" value="update_qty" name="update_cart_action" type="submit" onclick="return updatecart('<?php echo $item->getProductId()?>')">Update</button>
</td>
        <td class="total">
            <?php if($checkoutHelper->settings['display_tax_included']): ?>
            <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
            <?php else: ?>
            <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
            <?php endif; ?>
        </td>
    </tr>
    <?php 
	
	endforeach; ?>
  
</table>
</div>
<table class="onestepcheckout-totals">
    <?php 
	$tot = 0;
	$amt_due = 0;
	foreach($this->getTotals() as $total): 
		
	?>
    <?php if(!$total->getTitle()){continue;}?>
        <?php
        $fullInfo = $total->getFullInfo();

        if(!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']):
            foreach ($fullInfo as $info):
                $rates = current($info['rates']);
				
        ?>
          
            <tr>
                <td class="title"><?php echo $rates['title'] ?> (<?php echo $rates['percent'] ?>%)</td><td class="value"><?php echo $this->helper('checkout')->formatPrice($amount); ?></td>
            </tr>
        <?php endforeach;
        endif;?>
    <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
    <?php
    	$code = $total->getCode(); 
    	?>
        <td class="title<?php if($code == 'grand_total'){?> grand-title<?php }?>">
            <?php

		    $code = $total->getCode();
			$value = $total->getValue();

			if($code == 'subtotal' || $code == 'shipping' || $code == 'tax'){
					
					$tot += $value;
								
			}
			
            if($code == 'subtotal')    {
                $total_name = $this->__('Subtotal');
            }
           
		    elseif($code == 'shipping')    {
                $total_name = $this->__('Shipping');
                if($checkoutHelper->settings['display_tax_included'])   {
                    $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                }
                            }
            elseif($code == 'grand_total')    {
                $total_name = $this->__('Grand total');
				$name = $this->__('Grand total');
				$gt = $value;
            }elseif($code == 'discount'){
				
				if($total->getTitle()=='Discount (Curacao Credit)'){
					$total_name = $this->__('Curacao Credit');	
				}else{
					$total_name = $total->getTitle();
				}
				
				$amt_due = $value;
				//echo $amt_due = $tot + $value;
				
			}else   {
                $total_name = $total->getTitle();
            }
			//if($code != 'grand_total' && $total->getTitle()!='Discount (Curacao Credit)'){
            	echo $total_name;
			//}
			
            ?>
        </td>
       <td class="value<?php if($code == 'grand_total'){?> grand-price<?php }?>">
            <?php 
			//if($code != 'grand_total' && $total->getTitle()!='Discount (Curacao Credit)'){
				echo $this->helper('checkout')->formatPrice($value); 
			//}?>
        </td>
    </tr>
    <?php endforeach; 

	?>
  
    <!--<tr class="grand-total">
        <td class="title">
           <?php echo $name?>      </td>
        <td class="value">
            <?php echo $this->helper('checkout')->formatPrice($tot); ?>     </td>
    </tr>-->
    <?php if($Data != ''):?>
      <tr class="amount-due">
    	<td colspan="2">
        <?php 
			
			$balance = Mage::getSingleton('core/session')->getCustbalance();
			if($this->getGrandTotal()>$balance){
		?>
        	<p id="over-limit-error">
            	<?php echo $error_over_limit_1.'<strong>'.$balance.'</strong>'.$error_over_limit_2;?>
            </p>
            <?php }else{?>
            	<?php echo $error_dp?>
            <?php }?>
        </td>
    </tr>
     <!--   <tr class="amount-due">
        <td class="title">&nbsp;
         </td>
        <td class="value">&nbsp;
            </td>
    </tr>
    <tr class="grand-total">
        <td class="title"><?php //echo $paid_curacao;?>
         </td>
        <td class="value">
        	 <?php //$paid = $tot -$Data ?>

            <?php //echo $this->helper('checkout')->formatPrice($paid); ?>
            </td>
    </tr>
      <tr class="amount-due">
        <td class="title">&nbsp;
         </td>
        <td class="value">&nbsp;
            </td>
    </tr>-->
    <tr class="amount-due">
        <td class="title">
            <?php echo $due;?>        </td>
        <td class="value">
        <?php $amt_due ?>
        <?php $amt_due = $Data;?>
            <?php echo $this->helper('checkout')->formatPrice($amt_due); ?>     </td>
    </tr>
    
     <tr class="amount-due">
        <td class="title">&nbsp;
         </td>
        <td class="value">&nbsp;
            </td>
    </tr>
    
    <!-- <tr class="amount-due">
        <td class="title" colspan="2">
        	<span style="color:#F00; font-size:12px;"><?php //echo $pu;?></span><br /><img src="/images/credit_card.png">
         </td>
        
    </tr>-->
<?php endif?>
</table>


<script type="text/javascript">
//<![CDATA[
var total = <?php echo $this->getGrandTotal();?>;
    if(payment.reloadcallback){
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure'=>true)); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }
//]]>

function updatecart(pro_id){
	var proqty = jQuery("#prqty_"+pro_id).val();
	jQuery(".onestepcheckout-summary").html(' <div id="summery-loading"><center><img src="/images/gray_fade_small.gif" /></center></div>');
	jQuery.ajax({
				type: "POST",
				url: "/onestepcheckout/ajax/updatecart/?pro_id="+pro_id+"&qty="+proqty,
				success: function (data) {
					//location.reload();
					window.location = '/onestepcheckout/';
				}
			})
	
	return false;
}

function removeItem(pro_id){
	jQuery(".onestepcheckout-summary").html(' <div id="summery-loading"><center><img src="/images/gray_fade_small.gif" /></center></div>');
//	window.location = "/checkout/cart/delete/id/"+value
	jQuery.ajax({
				type: "POST",
				url: "/onestepcheckout/ajax/updatecart/?pro_id="+pro_id+"&qty=0",
				success: function (data) {
					//location.reload();
					window.location = '/onestepcheckout/';
				}
			})
	
	return false;
}

s.events="event8";
s.products="<?php echo $products?>";

</script>


   
