<?php
?>

<?php if (!$_set): ?>
<p style="text-align:center;font-size:0.8em"><a style="color:inherit;text-decoration:none" href="http://www.magify.com/">QuickShop Magento extension</a> by Magify <a style="color:inherit;text-decoration:none" href="http://www.magify.com/">Magento Themes</a> &amp; <a style="color:inherit;text-decoration:none" href="http://www.magify.com/">Magento Templates</a>
</p>
<?php endif ?>