<script type="text/javascript">
//<![CDATA[
	if (typeof Magify == 'undefined') Magify = {};
	Magify.QuickShop = {
		BASE_URL : '<?php echo str_replace("index.php/","",$this->getUrl()) ?>',
		QS_FRM_TYPE : <?php echo Mage::getStoreConfig('quickshop/general/size_type');?>,
		QS_FRM_WIDTH : <?php echo Mage::getStoreConfig('quickshop/general/frame_width');?>,
		QS_FRM_HEIGHT : <?php echo Mage::getStoreConfig('quickshop/general/frame_height');?>,
		QS_IMG: '<?php echo $this->getSkinUrl('images/magify_quickshop_preview.png'); ?>'
	};
	if(Magify.QuickShop.QS_FRM_TYPE == 0 ){
		Magify.QuickShop.QS_FRM_WIDTH = Magify.QuickShop.QS_FRM_WIDTH + "%";
		Magify.QuickShop.QS_FRM_HEIGHT = Magify.QuickShop.QS_FRM_HEIGHT + "%";
	}

//]]	
</script> 
