<?php
/**
 * Template for Mage_Page_Block_Html
 
 
 */

?>
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->

<head>
	<?php echo $this->getChildHtml('head') ?>
	
    <style type="text/css">
    	p{
			text-transform:none;
			font-size:14px;
		}
		h1{
			text-transform:none;
		}
    </style>

    <link href="/skin/frontend/enterprise/curacao-responsive/css/gwm.css" rel="stylesheet">
    
</head>

<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>

	<?php //echo $this->getChildHtml('after_body_start') ?>
	
	<header>
		
		<div class="container">
			<?php echo $this->getChildHtml('header') ?>
		</div><!--container-->
		
	</header>
	
	<div class="container">
	
		<div class="twenty columns breadcrumbs alpha">
			<?php echo $this->getChildHtml('breadcrumbs') ?>
		</div><!--breadcrumbs-->

		<div class="twenty columns breadcrumbs alpha">
			<div class="wrapper">
              
        			<!-- GWM Landing Page Code -->
                    	<div id="event">
                            <div id="flashHero">
                                <div class="coupon">KAU8S56</div>
                            </div>
                            <ul class="products">
                                <li class="firstcol">
                                    <a href="http://www.icuracao.com/pendants-necklaces-441"><img src="images/necklaces.jpg" border="0" /></a>
                                    <div class="gray">
                                        <a href="http://www.icuracao.com/pendants-necklaces-441" class="buynow">NECKLACES <span>&raquo;</span></a>
                                        <div class="clear"></div>
                                    </div>
                                </li>
                                <li>
                                    <a href="http://www.icuracao.com/watches"><img src="images/watches.jpg" border="0" /></a>
                                    <div class="gray">
                                        <a href="http://www.icuracao.com/watches" class="buynow">WATCHES <span>&raquo;</span></a>
                                        <div class="clear"></div>
                                    </div>
                                </li>
                                <li>
                                    <a href="http://www.icuracao.com/all-tv-s"><img src="images/televisions.jpg" border="0" /></a>
                                    <div class="gray">
                                        <a href="http://www.icuracao.com/all-tv-s" class="buynow">TELEVISIONS <span>&raquo;</span></a>
                                        <div class="clear"></div>
                                    </div>
                                </li>
                                <li class="firstcol">
                                    <a href="http://www.icuracao.com/home-theater-system"><img src="images/hometheater.jpg" border="0" /></a>
                                    <div class="gray">
                                        <a href="http://www.icuracao.com/home-theater-system" class="buynow">HOME THEATER <span>&raquo;</span></a>
                                        <div class="clear"></div>
                                    </div>
                                </li>
                                <li>
                                    <a href="http://www.icuracao.com/washer-dryers"><img src="images/washerdryer.jpg" border="0" /></a>
                                    <div class="gray">
                                        <a href="http://www.icuracao.com/washer-dryers" class="buynow">WASHER / DRYER <span>&raquo;</span></a>
                                        <div class="clear"></div>
                                    </div>
                                </li>
                                <li>
                                    <a href="http://www.icuracao.com/refrigerators"><img src="images/refridgerators.jpg" border="0" /></a>
                                    <div class="gray">
                                        <a href="http://www.icuracao.com/refrigerators" class="buynow">REFRIDGERATORS <span>&raquo;</span></a>
                                        <div class="clear"></div>
                                    </div>
                                </li>
                                <li class="firstcol">
                                    <a href="http://www.icuracao.com/dining-room-sets"><img src="images/diningroom.jpg" border="0" /></a>
                                    <div class="gray">
                                        <a href="http://www.icuracao.com/dining-room-sets" class="buynow">DINING ROOM <span>&raquo;</span></a>
                                        <div class="clear"></div>
                                    </div>
                                </li>
                                <li>
                                    <a href="http://www.icuracao.com/collections"><img src="images/bedroomsets.jpg" border="0" /></a>
                                    <div class="gray">
                                        <a href="http://www.icuracao.com/collections" class="buynow">BEDROOM SETS <span>&raquo;</span></a>
                                        <div class="clear"></div>
                                    </div>
                                </li>
                                <li>
                                    <a href="http://www.icuracao.com/mattress"><img src="images/mattresses.jpg" border="0" /></a>
                                    <div class="gray">
                                        <a href="http://www.icuracao.com/mattress" class="buynow">MATTRESSES <span>&raquo;</span></a>
                                        <div class="clear"></div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    <!-- End GWM Landing Page Code -->        
                     
                <div class="clear">&nbsp;</div>
                
              
            </div>
		</div>
	
      <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
        <?php echo $this->getAbsoluteFooter() ?>
	</div>        

		

</body>
</html>