<div class="store-select-holder">
	
<?php 
	$selectedState = '';
	$postData = Mage::app()->getRequest()->getPost();
		
	if(!empty($postData['state_list'])){
		$selectedState = $this->loadstate($postData['state_list']);
	}
	
	$city = $postData['City'];
		
	if(!empty($postData['zip_code'])){
		$address = $postData['zip_code'];
	}else{
		$address = $city.','.$selectedState;
	}
		
	$myaddress = urlencode($address);
	$url = "http://maps.googleapis.com/maps/api/geocode/json?address=$myaddress&sensor=false&region='US'";
	$getmap = file_get_contents($url);
	$googlemap = json_decode($getmap);
		
	foreach($googlemap->results as $res){
		$address = $res->geometry;
		$latlng = $address->location;
		$formattedaddress = $res->formatted_address;
		$latitude = $latlng->lat;
		$longitude = $latlng->lng;
	}
	$listStore = $this->getStores();
	$storeIds = array();

	foreach($listStore as $store){
		$storeIds[] = $store['info']->getId();
	}

	$helper = Mage::helper('pickup');
	$returnValue = $helper->getDetails($postData,implode(',',$storeIds));
	$availableStores = $returnValue['stores'];
	$sku = $returnValue['sku'];
	$storeData = array();

	for($i=0;$i<count($availableStores);$i++){
		$storeData[] = $this->loadStore($availableStores[$i])->getData();
	}
	
	$message = '';
	
	// New Updated stuff
	$product = Mage::getModel('catalog/product');
	$productId = $product->getIdBySku($sku);
	if ($productId) {
		$product->load($productId);
	}
	
?>
<?php //Adding Delivery Option ?>
<div class="select_store_hdng"><strong>Delivery Option</strong></div>
<?php
	$weight = $product->getWeight();
	 if((float)$product->getWeight()<1){
		$weight = 1;
	}
	
//	$content = file_get_contents('http://m113.icuracao.com/fedex/RateService_v13_php/php/RateWebServiceClient/Rate/RateWebServiceClient.php?zip='.$postData['zip_code'].'&weight='.$weight.'&shiptype=');
//echo $content = file_get_contents('http://m113.icuracao.com/fedex/RateService_v13_php/php/RateWebServiceClient/Rate/RateWebServiceClient.php?zip=90015&weight=1&shiptype=');

	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, 'http://m113.icuracao.com/fedex/RateService_v13_php/php/RateWebServiceClient/Rate/RateWebServiceClient.php?zip='.$postData['zip_code'].'&weight='.$weight.'&shiptype='.$product->getShprate());
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, true);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
	$content = curl_exec($ch);
	$info = curl_getinfo($ch);
	curl_close($ch);

	$shipinfo = explode("|",$content);

	Mage::getSingleton('core/session')->setEstimated($shipinfo[0]);
?>
<ul class="store-list-select">
	<li>
        <input type="radio"  onclick="setsessionvar('<?php echo $shipinfo[1]?>','<?php echo $sku; ?>','delivery');" />
        <label class="store-name">Fedex Ground</label>
        <label class="distance">$<?php echo $shipinfo[1]?></label>
    </li>
</ul>

<?php // End Delivery Option ?>

    <div class="select_store_hdng"><strong>Select Store (Store Pick up)</strong></div>
    
    	<ul class="store-list-select">
		<?php
		$availableStoreCount = 0;
		foreach($storeData as $row){
			$disinmiles = $this->getMiles($row['store_id'],$latitude,$longitude,'M');
			if($disinmiles<=25){
				$availableStoreCount++;	
		?>
			<li>
				<input type="radio" name="availablestore" value="<?php echo $row['store_id'];?>" onclick="setsessionvar(this.value,'<?php echo $sku; ?>','pickup');">
				<label class="store-name"><?php echo $row['store_name'];?></label>
				<label class="distance"><?php echo round($disinmiles,1, PHP_ROUND_HALF_UP);?> miles</label>
			</li>
		<?php 	
			}
		}
		if($availableStoreCount==0){
			echo '<li>There is no store near your area. Only available option is delivery to this area</li>';
		}
		
		?>
		</ul>
</div>