<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
         <div id="curacao_pay_line">
            <div id="curacao_pay_number">
                <ul>
                    <li>
                        <label for="<?php echo $_code ?>_check_no" class="required"><?php echo $this->__('Curacao Credit Card Number') ?><em>*</em></label>
						<span class="input-box">
							<input type="text" title="<?php echo $this->__('Curacao Credit Card Number') ?>" class="input-text required-entry input-text validate-digits validate-length maximum-length-8" id="curacao_cust_num" name="payment[check_no]" value="<?php echo $this->htmlEscape($this->getInfoData('check_no')) ?>" maxlength="8" />
						</span>
					</li>
				</ul>
            </div>
            <div id="curacao_pay_ccv">
            	<ul>
                    <li>
						<label for="ccv" class="required"><?php echo $this->__('CCV') ?><em>*</em></label>
                        <div class="input-box">
                            <div class="v-fix" id="curacao_ccv_number">
                                <input type="password" maxlength="4" title="<?php echo $this->__('CCV') ?>" class="input-text input-text required-entry validate-digits validate-length maximum-length-4" id="<?php echo $_code ?>_cc_cid" name="payment[ccv]" value="" />
                            </div>
                        </div>
                    </li>
				</ul>
            </div>
         </div>
         <div id="curacao_pay_line" class="curacao_pay_with_maiden">
         	<div id="curacao_dob_month">
			 	<label for="<?php echo $_code ?>_dob" class="required"><?php echo $this->__('Date Of Birth') ?><em>*</em></label>
        		<select class="required-entry" name="payment[cc_dob_month]" id="dobM">
                    <option selected="selected" value=""><?php echo $month?></option>
                    <option value="01">01 - January</option>
                    <option value="02">02 - February</option>
                    <option value="03">03 - March</option>
                    <option value="04">04 - April</option>
                    <option value="05">05 - May</option>
                    <option value="06">06 - June</option>
                    <option value="07">07 - July</option>
                    <option value="08">08 - August</option>
                    <option value="09">09 - September</option>
                    <option value="10">10 - October</option>
                    <option value="11">11 - November</option>
                    <option value="12">12 - December</option>
                </select>
            </div>
			<div id="curacao_dob_day">
	            <label for="<?php echo $_code ?>_dob" class="required">&nbsp;</label>
            	<select class="required-entry" name="payment[cc_dob_day]" id="dobD">
					<option value=""><?php echo $day?></option>
                    <?php for($i=1;$i<32;$i++){ ?>
                    <?php if($i<10){?>
                    <option value="<?php echo '0'.$i?>"><?php echo '0'.$i?></option>
                    <?php }else{?>
                    <option value="<?php echo $i?>"><?php echo $i?></option>
                    <?php }} ?>
				</select>
            </div>
			<div id="curacao_dob_year">
	            <label for="<?php echo $_code ?>_dob" class="required">&nbsp;</label>
            	 <select class="year required-entry" name="payment[cc_dob_year]" id="dobY">
					<option selected="selected" value=""><?php echo $year?></option>
					<?php for($i=(date("Y")-18);$i>1900;$i--){ ?>
					<option value="<?php echo $i?>"><?php echo $i?></option>
					<?php } ?>
				</select>
            </div>
			<div id="curacao_pay_ssn_maiden">
            	<ul>
                	<li>
                        <label for="<?php echo $_code ?>_check_date" class="required"><?php echo $this->__('Mother&acute;s Maiden Name') ?></label>
                        <span class="input-box">
                            <input type="text" title="<?php echo $this->__('Check Date:') ?>" class="input-text " id="<?php echo $_code ?>_check_date" name="payment[maiden]" value="<?php echo $this->htmlEscape($this->getInfoData('maiden')) ?>" />
                        </span>
                    </li>
                </ul>
            </div>
         </div>
         OR
         <div id="curacao_pay_line" class="curacao_pay_with_ssn">
			<div id="curacao_pay_ssn_maiden">
            	<ul>
                	<li>
                        <label for="<?php echo $_code ?>_check_date" class="required"><?php echo $this->__('Last 4 Digit of SSN') ?></label>
                        <span class="input-box">
                            <input type="password" maxlength="4" title="<?php echo $this->__('SSN:') ?>" class="input-text validate-digits validate-length maximum-length-4" id="<?php echo $_code ?>_check_date" name="payment[ssn]" value="" />
                        </span>
                    </li>
                </ul>
            </div>
         </div>
     </li>
</ul>

<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>