<?php
/**
 * Template for Mage_Page_Block_Html
 */
 
?>
<?php 
	$_storeId = Mage::app()->getStore()->getId();
	
?>
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
	<?php echo $this->getChildHtml('head') ?>
    <link media="all" href="/skin/frontend/enterprise/curacao-responsive/css/landingpage.css" type="text/css" rel="stylesheet">
</head>

<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>

	<header>
		<div class="container">
			<?php echo $this->getChildHtml('header') ?>
		</div><!--container-->
	</header>
	<div class="container">
		<div class="twenty columns breadcrumbs alpha">
			<?php echo $this->getChildHtml('breadcrumbs') ?>
		</div><!--breadcrumbs-->
			
		<div class="twenty columns alpha">
				<div class="wrapper">
               		<div class="maincontainer">
                        <!-- main banner start -->
                        <div class="main-banner">
                        <a href="http://www.icuracao.com/all-tv-s?dir=asc&order=price&tv_brand=20"><img src="images/banner-1.jpg" /></a>
                        </div>
                        <!-- main banner ends -->
                        <!-- content area starts -->
                        <div class="maincontent">
                        <!-- first row data starts -->
                        <div class="productsection">
                        <h1><img src="images/top-header.png" width="329" height="22" /></h1>
                        <div class="section">
                        <a href="http://www.icuracao.com/all-tv-s?dir=asc&order=price&tv_brand=20"><img src="images/tv.png" class="innerimage" /></a>
                        <div class="headeroutertv">
                        <a href="http://www.icuracao.com/all-tv-s?dir=asc&order=price&tv_brand=20"><img src="images/tv-header.png" width="141" height="12" /></a></div>
                        </div>
                        <div class="section1">
                        <a href="http://www.icuracao.com/refrigerators?dir=asc&order=price&tv_brand=20"><img src="images/lg-fridge.png" class="innerimagefridge" /></a>
                        <div class="headeroutertvminus"><img src="images/app.png" width="209" height="12" /></div>
                        </div>
                        <div class="section1">
                        <a href="http://www.icuracao.com/refrigerators?dir=asc&order=price&tv_brand=20"><img src="images/lg-washing-machines.png" class="innerimagefridge" /></a>
                        <div class="headeroutertvminus"><img src="images/washer.png" width="246" height="12" /></div>
                        </div>
                        </div>
                        <div class="clr"></div>
                        <!-- first row data ends -->
                        <!-- second product area starts -->
                        <div class="productsectionsavings">
                        <div class="header2img"><img src="images/top-header-1.png"  /></div><div class="clr"></div>
                        <div class="section2">
                        <a href="http://www.icuracao.com/lg-47la6200-led-47-1080p-120hz-3d-wifi-smart-tv.html"><img src="images/offer1.png" class="offerimg" /></a>
                        <div class="clr"></div>
                        <div class="offercontent">
                        <strong>So Smart, It's Simple</strong><br />
                        47" Class Cinema 3D 1080p 120Hz LED TV with Smart TV (46.9” DIAGONAL)<br />
                        47LA6200<br />
                        Size: 42", 47", 50", 55", 60"<br /><br />
                        <ul>
                          <li>LG Smart TV
                            • Cinema 3D    </li>
                          <li>TruMotion 120Hz    </li>
                          <li>Full HD 1080p Resolution    </li>
                          <li>ENERGY STAR® Most Effecient 
                            2013 Television</li>
                        </ul>
                        <div class="ordernow">
                        <div class="saveprice">Reg. Price : <strike>$1,199.99</strike><span class="saveprice"> </span></div>
                        <div class="priceleft">$849.<sup>95</sup>
                          <div class="saveprices">( You Save: 29%)</div>
                        </div>
                        <div class="buttonright">
                        <a href="http://www.icuracao.com/lg-47la6200-led-47-1080p-120hz-3d-wifi-smart-tv.html"><button onclick="productAddToCartForm.submit(this)" class="button btn-add-to-cart" title="Add Item to Cart" type="button"><span><span>Shop Now</span></span></button></a>
                        </div>
                        </div>
                        </div>
                        </div>
                        <div class="section3">
                        <a href="http://www.icuracao.com/home-theater-system/lg-bh9430pw-9-1-channel-3d-smart-wifi-tall-speaker-home-theater-system.html"><img src="images/offer2.png" class="offerimg" /></a>
                        
                        <div class="clr"></div>
                        <div class="offercontent">
                        <strong>Take Your Home Theater 
                        to the Next Level</strong><br />
                        3D-Capable 9.1 Ch Aramid Fiber Blu-ray <br />
                        Disc™ Home Theater System with Smart TV<br />
                        BH9430PW<br /><br />
                        <ul>
                          <li>Aramid Fiber</li>
                          <li>LG Smart TV   </li>
                          <li>9.1 Channel Immersive Sound   </li>
                          <li>ENERGY STAR® Most Effecient 
                            3D Blu-ray</li>
                        </ul>
                        <br />
                        <div class="ordernow">
                        <div class="saveprice">Reg. Price : <strike>$799.99</strike><span class="saveprice"> </span></div>
                        <div class="priceleft">$699.<sup>95</sup>
                          <div class="saveprices">( You Save: 12%)</div>
                        </div>
                        <div class="buttonright">
                        <a href="http://www.icuracao.com/home-theater-system/lg-bh9430pw-9-1-channel-3d-smart-wifi-tall-speaker-home-theater-system.html">
                        	<button onclick="productAddToCartForm.submit(this)" class="button btn-add-to-cart" title="Add Item to Cart" type="button"><span><span>Shop Now</span></span></button>
                        </a>
                        </div>
                        </div>
                        </div>
                        </div>
                        <div class="section3">
                        <a href="http://www.icuracao.com/lg-wt1201cv-5-2-cu-ft-high-efficiency-top-load-washer-stainless-steel.html"><img src="images/offer3.png" class="offerimg" /></a>
                        
                        <div class="clr"></div>
                        <div class="offercontent">
                        <strong>A Revolutionary Spin On Laundry</strong><br />
                        4.5 cu. ft. Ultra Large Capacity Top <br />
                        Load Washer with Front Control <br />
                        Design and WaveForce™ Technology<br />
                        WT1201CV<br />
                        COLOR :  Graphite Steel   White<br />
                        <ul>
                          <li>Ultra Large 4.5 cu. ft. Capacity</li>
                          <li>Front Control Design</li>
                          <li>ColdWash™ Technology </li>
                          <li>Direct Drive Motor 10 Year Limited Warranty</li>
                        </ul>
                        <div class="ordernow">
                        <div class="saveprice">Reg. Price : <strike>$899.99</strike><span class="saveprice"> </span></div>
                        <div class="priceleft">$799.<sup>95</sup>
                          <div class="saveprices">(  You Save: 11%)</div>
                        </div>
                        <div class="buttonright">
                        <a href="http://www.icuracao.com/lg-wt1201cv-5-2-cu-ft-high-efficiency-top-load-washer-stainless-steel.html"><button onclick="productAddToCartForm.submit(this)" class="button btn-add-to-cart" title="Add Item to Cart" type="button"><span><span>Shop Now</span></span></button></a>
                        </div>
                        </div>
                        </div>
                        </div>
                        </div>
                        <!-- second product area ends -->
                        </div>
                        <!-- content area ends -->
                        <div class="clr"></div>
                        </div>

                </div>
            </div>
		</div>
	
      <?php echo $this->getChildHtml('footer') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
        <?php echo $this->getAbsoluteFooter() ?>
	</div>        

		

</body>
</html>
<script type="text/javascript">
	function createrecord() {
		jQuery("#elcapoform").hide("slow");
		jQuery("#equipo_link").show("slow")			
		var formdata = jQuery('form').serializeArray();
		jQuery.ajax({
			type: "POST",
			url: "custom/addequipo.php",
			data: formdata,
			success: function (data) {
				if(data==1){
					jQuery("#equipo-response").show("slow");
					jQuery("#equipo_link").hide("slow")
				}else{
					alert(data)
					jQuery("#elcapoform").show("slow");
					jQuery("#equipo_link").hide("slow")
				}
			  }
		})
	
		return false;
	}	
</script>