<?php
$step_counter = 1;
$helper = Mage::helper('onestepcheckout/checkout');

	$Data = Mage::getSingleton('core/session')->getCuracacaodp();
	$authenticate = Mage::getSingleton('core/session')->getAuthentication();
	$authention_error = Mage::getSingleton('core/session')->getAuthenticationerror();
	$_storeId = Mage::app()->getStore()->getId();
	if($_storeId == 1){
		$due = 'Amount Due Today';
		$downpaymentneeded = 'To process your order, an initial payment of  <strong>$'.number_format((float)$Data, 2, '.', '').'</strong> is required. ';
		$billingaddress = "Billing And Shipping Information";
		$billing = "Billing Address";
		$shippingaddress = "Shipping Address";
		if($authention_error == 'credit_error'){
			$authenticatemsg = "Your account may have an outstanding issue. Please contact our customer support at (866)410-1611 for assistance and we will be happy to sort this out for you. Thank you.";
			
		}elseif($authention_error =='acc_error'){
			$authenticatemsg = "Your account has not been activated yet.  To review the status of your account or update any information please contact our customer support at (866)410-1611.  Thank you.";
		}elseif($authention_error == 'acc_lock'){
			$authenticatemsg = "Unfortunately we are unable to verify your account information. For security reasons, please contact customer service at (866)410-1611.  Thank you.";
		}elseif(trim($authention_error) == 'acc_no_error'){
			$authenticatemsg = "Please provide valid number.";
		}else{
			$authenticatemsg = "We were unable to verify the information you have provided. Please re-enter the information or call our customer support at (866)410-1611. Thank you. Fields didnt match : ".$authention_error;
		}
		$required = 'Required Fields';
		
	} else {
		$due = 'Pago Inicial Requerido';
		$downpaymentneeded = 'Un pago inicial es requerido para poder procesar su orden. Por favor ingrese la informaci&oacute;n de su pago a continuaci&oacute;n:';
		$billingaddress = "Dirección de Facturaci&oacute;n";
		$billing = "Dirección de Facturaci&oacute;n"; 	
		$shippingaddress = "Dirección de Envío";
		if($authention_error == 'credit_error'){
			
			$authenticatemsg = 'Nuestros registros indican un problema de pagos pendientes en su cuenta. Para asistencia, por favor comuníquese con nuestro servicio de atención al cliente 1(866)410-1611, nuestros representantes le ayudarán gustosamente.';
			
		}elseif($authention_error =='acc_error'){
			$authenticatemsg = "Su cuenta no ha sio activada todavía. Para revisar el estado de su cuenta ó actualizar cualquier información pendiente por favor comuníquese con nuestro servicio de atención al cliente al 1(866)410-1611. Gracias.";
		}elseif($authention_error == 'acc_lock'){
			$authenticatemsg = "Desafortunadamente no fue posible verificar la información de su cuenta en este momento. Por razones de seguridad, por favor comuníquese con nuestro servicio al cliente al 1-866-410-1611.";
		}elseif($authention_error == 'acc_no_error'){
			$authenticatemsg = "Por favor, introduzca un número válido en este campo";
		}else{
			$authenticatemsg = "No hemos podido verificar la información que usted ha proporcionado. Por favor ingrese nuevamente la información requerida ó llame a nuestro servicio de atención al cliente al 1(866)410-1611". $authention_error;
		}
		$required = "Campos Requeridos";
	}

?>

<?php
	// Check if the user logged in or not
		$server = '192.168.100.121';
		$user = 'curacaodata';
		$pass = 'curacaodata';
		$db = 'icuracaoproduct';
		
		
		$link = mysql_connect($server,$user,$pass);
		
		mysql_select_db($db,$link);
		$customer = Mage::getSingleton('customer/session');
		
		if(Mage::getSingleton('core/session')->getCheckouttrackid()){
			if($customer->isLoggedIn()) {
				$sql = 'update checkouttrack set loggedin = 1 where checkouttrackid = "'.Mage::getSingleton('core/session')->getCheckouttrackid().'"';
			}else{
				$sql = 'update checkouttrack set loggedin = 0 where checkouttrackid = "'.Mage::getSingleton('core/session')->getCheckouttrackid().'"';
			}
				mysql_query($sql);
		}else{
			if($customer->isLoggedIn()) {
				 $sql = 'insert into checkouttrack(loggedin) values("1")';
			}else{
				 $sql = 'insert into checkouttrack(loggedin) values("0")';
			}
				mysql_query($sql);
				$track = mysql_insert_id();
				Mage::getSingleton('core/session')->setCheckouttrackid($track);
		}
		
	// End logged in 
?>


<?php if(!$this->canCheckout() || !$this->validateMinimumAmount()): ?>
    <?php if($this->settings['checkout_title']): ?>
        <h1 class="onestepcheckout-title"><?php echo $this->settings['checkout_title']; ?></h1>
    <?php endif; ?>

    <?php if($this->canCheckout() && !$this->validateMinimumAmount()): ?>
    <p><?php echo Mage::getStoreConfig('sales/minimum_order/description'); ?></p>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
    <?php else: ?>
    <p><?php echo $this->__('You need to have products in your cart to checkout, and your cart is empty.'); ?></p>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
    <?php endif; ?>
<?php else: ?>

<form id="onestepcheckout-form" method="post" action="<?php echo $this->getUrl('onestepcheckout', array('_secure'=>true)); ?>">
	<fieldset class="group-select" style="margin: 0;">
	
    <input type="hidden" name="checkouttrackid" value="<?php echo Mage::getSingleton('core/session')->getCheckouttrackid()?>" />
    
	<?php if($this->settings['checkout_title']): ?>
	    <h1 class="onestepcheckout-title"><?php echo $this->settings['checkout_title']; ?></h1>
	<?php endif; ?>
	
	<?php if($this->settings['checkout_description']): ?>
	    <p class="onestepcheckout-description"><?php echo $this->settings['checkout_description']; ?></p>
	<?php endif; ?>
	
	
	
		<?php if(isset($this->formErrors['unknown_source_error'])): ?>
		<div class="onestepcheckout-error">
		    <?php echo $this->formErrors['unknown_source_error']; ?>
		</div>
		<?php endif; ?>
		<div class="checkout-holder">
			<div class="onestepcheckout checkout-left columns alpha checkoutcontainer onestepcheckout-skin-<?php echo $this->settings['skin']; ?> <?php if(Mage::helper('onestepcheckout')->isEnterprise()): ?>onestepcheckout-enterprise<?php endif; ?>">
			    <div class="onestep-header">
			        <h5><?php echo $billingaddress; ?></h5>
			    </div>
			    <div class="checkout section">
					<div id="billing_address">
			            <script type="text/javascript">
			            	var billing = new Billing();
			            </script>
			                    
			            <ul class="checkout-column">
			                <li>
			                   <!-- <p class="onestepcheckout-numbers">
			                    	<span class="number"><?php //echo $step_counter++; ?></span><?php echo $billingaddress; ?>
			                    </p>-->
			                        <?php if(isset($this->formErrors['billing_error']) && count($this->formErrors['billing_errors']) > 0): ?>
			                        <div class="onestepcheckout-error">
			                            <?php echo $this->__('Please check red fields below and try again.'); ?>
			                        </div>
			                        <?php endif; ?>
			                </li>
			                <?php if ($this->customerHasAddresses()): ?>
			                <li>
			                   <!-- <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>-->
			                    <div class="input-box">
			                        <?php //echo $this->getAddressesHtmlSelect('billing') ?>
			                    </div>
			                    
			                    <div id="address-left">
			                    	<h3>Billing Address:</h3>
			                    	 <div id="billingAddress">
									 <?php 
									 	$customer = Mage::getSingleton('customer/session')->getCustomer();
											$customerAddressId = $customer->getDefaultBilling();
											if ($customerAddressId){
												   $address = Mage::getModel('customer/address')->load($customerAddressId);
												  echo '<p>'.$htmlAddress = $address->format('html').'</p>';
											}
											
										?>
			                            </div>
			                               <input name="billing_address_id" id="billingAddId" type="hidden" value="<?php echo $address->getId();?>" /></p>
			                            
			                            
			                            
			                            <a href="#TB_inline?height=580&width=781&inlineId=billingContent" class="thickbox" title="Billing Address">Change</a>
			                            
			                                                <?php $uncheck = (!empty($_POST['billing']) && empty($_POST['billing']['use_for_shipping']));?>
			                    <?php if($this->differentShippingAvailable()): ?>
			                        <div class="input-box input-different-shipping">
			                            <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" class="checkforshipping" value="1" <?php echo (($this->sameAsBilling() && !$uncheck) ? 'checked="checked" ':'')?>/>
			                            <label for="billing:use_for_shipping_yes"><?php echo $this->__('Ship to the same address')?></label>
			                        </div>
			                    <?php else: ?>
			                        <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" checked="checked" />
			                    <?php endif; ?>
			
			                            
			<div id="billingContent" style="display:none">
				<div id="billingaddleft">	
			    <h3>Choose a Billing Address:</h3>
			    
					<?php 
						
								foreach ($customer->getAddresses() as $address)
								 {
								
									echo '<p id="billingAdd'.$address->getId().'">'.$address->format('html').'</p>';
								?>
			                    <div style="clear:both"></div>
			                    <a id="billingadd<?php echo $address->getId() ?>" href="" onclick="return usebillingadd('<?php echo $address->getId();?>')">Use This Address</a>
			                    <a id="billingremove<?php echo $address->getId() ?>" href="" onclick="return removebillingadd('<?php echo $address->getId();?>')">Remove</a>
			<!--                    <button id="checkoutButton" onclick="return usebillingadd('<?php echo $address->getId();?>')"><span><span>Use This Address</span></span></button>-->
			                    
			                    <!--<button value="Apply Coupon" onclick="return usebillingadd('<?php echo $address->getId();?>')" class="button" title="Apply Coupon" type="button"><span><span>Use This Address</span></span></button>-->
			                    
			                   <div style="clear:both" style="margin-bottom:25px;"></div>
			                    <?php 
									//echo '<input type="button" onclick="return useshipping()"';
			
								 }
			
					?>	
					</div>	
			        <div id="billingaddright">
			        	<h3>Add a Billing Address:</h3>
			        
			   			 <?php echo $this->getChildHtml('billing_address');?><br />
			            <div style="float: right;">
			             <button id="checkoutButton" title="Submit Address" onclick="return custombillingadd()"><span><span>Submit Address</span></span></button>
			            </div>
			
			    </div>
			        </div>
			                            
			                    </div>
			                    
			                    <div id="address-right">
			                    	<h3>Shipping Address:</h3>
			                    	<div id="shippingAdd">
			                         <?php 
											$customerAddressId = $customer->getDefaultShipping();
											if ($customerAddressId){
												   $address = Mage::getModel('customer/address')->load($customerAddressId);
												  echo  '<p>'.$htmlAddress = $address->format('html').'</p>';
											}
											
										?>
			                            </div>
			                            <div id="newshippingAdd" style="display:none">
			                               
			                            </div>
			                            <input name="shipping_address_id" type="hidden" value="<?php echo $address->getId();?>" id="shippingAdd_id" />
			                           
			<a href="#TB_inline?height=580&width=781&inlineId=myOnPageContent" class="thickbox" title="Shipping Address">Change</a>
			<div id="myOnPageContent" style="display:none">
			<div id="shippingaddleft">
			 <h3>Choose a Shipping Address:</h3>
					<?php 
						
								foreach ($customer->getAddresses() as $address)
								 {
								
									echo '<p id="shipping'.$address->getId().'">'.$address->format('html').'</p>';
								?>
			                    <div style="clear:both"></div>
			                   <!-- <button value="Apply Coupon" onclick="return useshippingadd('<?php echo $address->getId();?>')" class="button" title="Apply Coupon" type="button"><span><span>Use This Address</span></span></button>-->
			                   <a id="shippingadd<?php echo $address->getId() ?>" href="" onclick="return useshippingadd('<?php echo $address->getId();?>')">Use This Address</a>
			                    <a id="shippingremove<?php echo $address->getId() ?>" href="" onclick="return removebillingadd('<?php echo $address->getId();?>')">Remove</a>
			                  <!-- <button id="checkoutButton" onclick="return useshippingadd('<?php echo $address->getId();?>')"><span><span>Use This Address</span></span></button>-->
			       
			                    <div style="clear:both" style="margin-bottom:25px;"></div>
			                    <?php 
									//echo '<input type="button" onclick="return useshipping()"';
			
								 }
			
					?>	
			        
			        
				</div>
			    <div id="shippingaddright">
			    	 <h3>Add a Shipping Address:</h3>
			   	   <div id="">
			                <ul>
			                    <?php echo $this->getChildHtml('shipping_address');?>
			                    <?php $addressAttributes = $this->getChild('customer_form_shipping_address_user_defined_attributes');?>
			                    <?php if ($addressAttributes): ?>
			                        <?php $addressAttributes->setEntity($this->getQuote()->getShippingAddress())->setEntityType('customer_address');?>
			                        <?php $addressAttributes->setFieldIdFormat('shipping:%1$s')->setFieldNameFormat('shipping[%1$s]');?>
			                        <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
			                    <?php endif;?>
			                </ul>
			                
			                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getQuote()->getShippingAddress()->getId() ?>" id="shipping:address_id" />
			                <!-- END LIST OF SHIPPIING FIELDS -->
			            </div>
						<div style="float: right;">
			            <button id="checkoutButton" onclick="return customshippingadd()"  title="Submit Address" type="button"><span><span>Submit Address</span></span></button>             </div>                                                                
			   	                                                                       
			    </div>		
			        </div>
			                    </div>
			                    
			                </li>
							<?php else: ?>
			                <div id="address-left">
			                    <ul class="seven columns">
			                        <li class="shipping-address-title">
			                        <?php echo $billing; ?>
			                    </li>
			                    
			                    </ul>
			                	<?php echo $this->getChildHtml('billing_address');?>
			                
			                
			                </div>	
			                    
			                <div id="address-right">
			            		<ul class="seven columns">
			                        <li class="shipping-address-title">
			                            <?php echo $shippingaddress; ?>
			                        </li>
			                        
			                </ul>
			                
			                <div id="shippingmsg">Same as billing address</div>
			                	 <?php if($this->differentShippingAvailable()): ?>
			        <div id="shipping_address" style="display:none" <?php  echo (($this->sameAsBilling() && !$uncheck) ? 'style="display: none"': false);?>>
			            <script type="text/javascript">
			                var shipping = new Shipping();
			            </script>
			            <ul class="seven columns">
			                <?php if ($this->customerHasAddresses()): ?>
			                   <li class="form-alt">
			                       <!--<label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>-->
			                       <div class="input-box"><?php //echo $this->getAddressesHtmlSelect('shipping') ?></div>
			                   </li>
			                <?php endif ?>
			                <li id="shipping_address_list" <?php if($this->customerHasAddresses() && !$this->getNewAddressSelectValueOnError('shipping')) { echo '  style="display: none;" '; } ?>>
			                    <div id="">
			                        <ul>
			                            <?php echo $this->getChildHtml('shipping_address');?>
			                            <?php $addressAttributes = $this->getChild('customer_form_shipping_address_user_defined_attributes');?>
			                            <?php if ($addressAttributes): ?>
			                                <?php $addressAttributes->setEntity($this->getQuote()->getShippingAddress())->setEntityType('customer_address');?>
			                                <?php $addressAttributes->setFieldIdFormat('shipping:%1$s')->setFieldNameFormat('shipping[%1$s]');?>
			                                <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
			                            <?php endif;?>
			                        </ul>
			                        <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getQuote()->getShippingAddress()->getId() ?>" id="shipping:address_id" />
			                        <!-- END LIST OF SHIPPIING FIELDS -->
			                    </div>
			                </li>
			            </ul>
			        </div>
			    <?php endif; ?>
			                </div>	
			                <?php endif; ?>
			                <li>
			                    <div  id="billing_address_list"  <?php if(!isset($this->formErrors['billing_error']) && count($this->formErrors['billing_errors']) == 0): ?><?php echo (($this->customerHasAddresses() && !$this->getNewAddressSelectValueOnError('billing')) ? 'style = "display:none"' : false ); ?><?php endif?>>
			                       <!-- <ul class="seven columns">-->
			                            <?php //echo $this->getChildHtml('billing_address');?>
			                            <?php $addressAttributes = $this->getChild('customer_form_billing_address_user_defined_attributes');?>
			                            <?php if ($addressAttributes): ?>
			                                <?php $addressAttributes->setEntity($this->getQuote()->getBillingAddress())->setEntityType('customer_address');?>
			                                <?php $addressAttributes->setFieldIdFormat('billing:%1$s')->setFieldNameFormat('billing[%1$s]');?>
			                                <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
			                            <?php endif;?>
			                            <?php $customerAttributes = $this->getChild('customer_form_customer_user_defined_attributes');?>
			                            <?php if ($customerAttributes): ?>
			                                <?php $customerAttributes->setEntityModelClass('customer/customer')->setFieldIdFormat('billing:%1$s');?>
			                                <?php $customerAttributes->setFieldNameFormat('billing[%1$s]')->setShowContainer(false);?>
			                                <?php echo $customerAttributes->setExcludeFileAttributes(true)->toHtml()?>
			                            <?php endif;?>
			                       <!-- </ul>-->
			                    </div>
			                </li>
			              
			                <li>
					        <?php if($this->settings['enable_newsletter']): ?>
					            <div class="onestepcheckout-enable-newsletter">
					                <input type="checkbox" id="id_subscribe_newsletter" name="subscribe_newsletter" value="1" <?php if($this->settings['newsletter_default_checked']): ?>checked="checked"<?php endif; ?> />
					                <label for="id_subscribe_newsletter"><?php echo $this->__('Subscribe to our newsletter'); ?></label>
					            </div>
					        <?php endif; ?>
			                </li>
			               
			            </ul>
			        </div>
				<div id="req_field"><em>*</em> <?php echo $required?></div>
			   
				</div>
				<br />
				<div id="shipping_method_checkout">
				    <h5><?php echo $this->__('Shipping method'); ?></h5>
			    </div>
			    
			    <div class="checkout section">
			        <?php if(!$this->isVirtual()): ?>
			            <?php if(Mage::getStoreConfig('onestepcheckout/general/hide_shipping_method')):?>
			                <?php if(isset($this->formErrors['shipping_method']) && $this->formErrors['shipping_method']): ?>
			                    <div class="onestepcheckout-error onestepcheckout-shipment-method-error">
			                        <?php echo $this->__('Please choose a shipping method.'); ?>
			                    </div>
			                <?php endif; ?>
			                <?php echo $this->getChildHtml('choose-shipping-method'); ?>
			            <?php else:?>
			                <div class="onestepcheckout-shipping-method">
			                   <!-- <p class="onestepcheckout-numbers">
			                    	<span class="number"><?php //echo $step_counter++; ?></span>
			                    	<?php echo $this->__('Shipping method'); ?>
			                    </p>
			-->
			                    <?php if(isset($this->formErrors['shipping_method']) && $this->formErrors['shipping_method']): ?>
			                    <div class="onestepcheckout-error onestepcheckout-shipment-method-error">
			                        <?php echo $this->__('Please choose a shipping method.'); ?>
			                    </div>
			                    <?php endif; ?>
			
			                    <div class="onestepcheckout-shipping-method-block">
			                        <?php echo $this->getChildHtml('choose-shipping-method'); ?>
			                    </div>
			                </div>
			            <?php endif; ?>
			        <?php endif; ?>
				</div>
			    
			    <div class="onestep-header">
			        <h5><?php echo $this->__('Payment method'); ?></h5>
			    </div>
			    
			    <div class="checkout section">
			<!--     <p class="onestepcheckout-numbers">
			            	<span class="number"><?php //echo $step_counter++; ?></span>
			            	<?php echo $this->__('Payment method'); ?>
			            </p> 
			-->    <?php $grandTotal = Mage::getModel('checkout/cart')->getQuote()->getGrandTotal(); ?>
			    <!--Payment Method-->
			   
			        <?php if(Mage::getStoreConfig('onestepcheckout/general/hide_payment_method')):?>
			            <?php if(!empty($this->formErrors['payment_method'])): ?>
			            <div class="onestepcheckout-error onestepcheckout-payment-method-error">
			                <?php echo $this->__('Please choose a payment method.'); ?>
			            </div>
			            <?php endif; 
						?>
			            
			            <?php if(!empty($this->formErrors['payment_method_error'])): ?>
			                <div class="onestepcheckout-error onestepcheckout-payment-method-error">
			                    <?php echo $this->__('Please enter valid details below.'); ?>
			                </div>
			            <?php endif; ?>
			            <?php echo $this->getChildHtml('choose-payment-method'); ?>
			        <?php else: ?>
			           <!-- <p class="onestepcheckout-numbers">
			            	<span class="number"><?php //echo $step_counter++; ?></span>
			            	<?php echo $this->__('Payment method'); ?>
			            </p>-->
			            <?php if(isset($this->formErrors['payment_method']) && $this->formErrors['payment_method']): ?>
			                <div class="onestepcheckout-error onestepcheckout-payment-method-error">
			                    <?php echo $this->__('Please choose a payment method.'); ?>
			                </div>
			            <?php else: ?>
			                <?php if(isset($this->formErrors['payment_method_error'])): ?>
							<?php if($Data == ''):?>
			                <?php if($authenticate != '0'){?>
							
			                    
			               
			                
						  	<?php }elseif($authention_error != ''){
								
								$sql = 'update checkouttrack set authentication_error = 1, auth_track_id = '.Mage::getSingleton('core/session')->getTrackingId().' where checkouttrackid = "'.Mage::getSingleton('core/session')->getCheckouttrackid().'"';
								mysql_query($sql);
								
								?>
			              		<div class="onestepcheckout-error onestepcheckout-payment-method-error">
									<?php echo $authenticatemsg; ?>
			                    </div>
							<?php }else{?>  	
						     	<div class="onestepcheckout-error onestepcheckout-payment-method-error">
			                        <?php echo $this->__('Please enter valid details below.'); ?>
			                    </div>
			                <?php } else:?>
			                <div class="onestepcheckout-error onestepcheckout-payment-method-error">
			                    <?php echo $downpaymentneeded; ?>
			                </div>
						   <?php endif; ?>
			               <?php endif; ?>
						<?php  endif; ?>
			           
						
						
			            <?php echo $this->getChildHtml('choose-payment-method'); ?>
			
			            <div class="tool-tip" id="payment-tool-tip" style="display:none;">
			                <div class="btn-close">
			                    <a href="javascript:void(0);" id="payment-tool-tip-close"><img src="<?php echo $this->getSkinUrl('images/btn_window_close.gif') ?>" alt="<?php echo $this->__('Close') ?>" /></a>
			                </div>
			                <div class="block-content">
			                <img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" />
			                </div>
			            </div>
			            
			            <div class="tool-tip" id="payment-tool-tip-curacao" style="display:none;">
			                <div class="btn-close">
			                    <a href="javascript:void(0);" id="payment-tool-tip-curacao-close"><img src="<?php echo $this->getSkinUrl('images/btn_window_close.gif') ?>" alt="<?php echo $this->__('Close') ?>" /></a>
			                </div>
			                <div class="block-content">
			                <?php if($_storeId==1){?>
			                	<img src="<?php echo $this->getSkinUrl('images/whatsthis_ccv.jpg') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" />
			                <?php }else{?>
			                	<img src="<?php echo $this->getSkinUrl('images/whatsthis_ccv_es.jpg') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" />
			                <?php }?>
			                </div>
			            </div>
			            
			        <?php endif; ?>
			        
			        
			    </div>
			
			
			
			   <!-- </div>-->
			    
			    
			    
			    <!--End Payment Method-->
			
			 <div class="checkout section last place-holder">
			    	<div class="onestepcheckout-place-order-wrapper">
			        	<button type="button" title="<?php echo $this->__('Place order now'); ?>" id="onestepcheckout-place-order" class="large orange onestepcheckout-button onestepcheckout-place-order" onclick="javasctipt:void(0);"><span><span><?php echo $this->__('Place order now'); ?></span></span></button>
			        </div>
				</div>
			    
				
				
			</div>
			<div class="onestepcheckout checkout-right columns alpha checkoutcontainer onestepcheckout-skin-<?php echo $this->settings['skin']; ?> <?php if(Mage::helper('onestepcheckout')->isEnterprise()): ?>onestepcheckout-enterprise<?php endif; ?>">
				<div class="onestep-header">
			        <h5><?php echo $this->__('Review your order'); ?></h5>
			    </div>
			    
			    <div class="checkout section">
			
			        <!--<p class="onestepcheckout-numbers">
			        	<span class="number"><?php //echo $step_counter++; ?></span>
			        	<?php echo $this->__('Review your order'); ?>
			        </p>-->
			
			        <div class="onestepcheckout-summary">
			            <?php echo $this->getChildHtml('summary'); ?>
			        </div>
			
			        <?php if($this->settings['enable_comments']): ?>
			            <div class="onestepcheckout-comments">
			                <label for="id_comments"><?php echo $this->__('Comments'); ?></label>
			                <textarea id="id_comments" name="onestepcheckout_comments"><?php if(isset($_POST['onestepcheckout_comments'])) { echo $_POST['onestepcheckout_comments']; } ?></textarea>
			            </div>
			        <?php endif; ?>
			
			        <?php if($this->settings['enable_gift_messages']): ?>
			            <div id="onestepcheckout-giftmessages">
			            <div class="onestepcheckout-giftmessagecontainer">
			            <?php echo $this->helper('onestepcheckout/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
			            </div>
			            </div>
			        <?php endif; ?>
			
			        <?php $_extraProductsHelper = Mage::helper('onestepcheckout/extraproducts'); ?>
			            <?php if($_extraProductsHelper->hasExtraProducts()): ?>
			            <div class="onestepcheckout-extraproducts">
			                <ul>
			                <?php foreach($_extraProductsHelper->getExtraProducts() as $product): ?>
			                    <li><input type="checkbox" class="onestepcheckout-extra-product"
			                    <?php if($_extraProductsHelper->productInCart($product->getId())): ?>
			                        checked="checked" <?php endif; ?>
			                        name="extra_products_<?php echo $product->getId(); ?>"
			                        id="id_extra_product_<?php echo $product->getId(); ?>" /> &nbsp;
			                    <label for="id_extra_product_<?php echo $product->getId(); ?>"> <?php echo $product->getName(); ?>
			                    <span><?php echo Mage::helper('checkout')->formatPrice($product->getPrice()); ?></span>
			                    </label></li>
			                    <?php endforeach; ?>
			                </ul>
			            </div>
			
			            <script>
			            Event.observe(window, 'load', function() {
			                $$('input.onestepcheckout-extra-product').invoke('observe', 'click', function(e) {
			                    var id_temp = e.element().id.split('id_extra_product_');
			                    if(id_temp.length == 2) {
			                        var product_id = id_temp[1];
			                        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_extra_product'); ?>';
			                        var parameters = {
			                            product_id: product_id
			                        }
			
			                        if(!e.element().checked) {
			                            parameters['remove'] = 1;
			                        }
			
			                        var summary = $$('div.onestepcheckout-summary').first();
			                        summary.update('<div class="loading-ajax">&nbsp;</div>');
			
			                        new Ajax.Request(url, {
			                            method: 'post',
			                            parameters: parameters,
			                            onSuccess: function(transport)  {
			                                summary.update(transport.responseText);
			                            }
			                        });
			                   };
			                });
			            });
			        </script>
			        <?php endif; ?>
			
			        <?php
			        /**
			         * Feedbackdropdown start
			         */
			        ?>
			        <?php if(!empty($this->settings['feedback']['enable_feedback']) && !empty($this->settings['feedback']['feedback_values'])):?>
			            <?php
			                $selectedFeedBackFields = $this->getRequest()->getPost('onestepcheckout-feedback', false);
			                $feedbackValues = unserialize($this->settings['feedback']['feedback_values']);
			            ?>
			            <div class="onestepcheckout-feedback" id="">
			                <label for="id_feedback"><?php echo $this->__('How did you hear about us?'); ?></label>
			                <select style="" name="onestepcheckout-feedback" id="id_feedback" defaultvalue="">
			                    <option value=""><?php echo $this->__('Please choose'); ?></option>
			                    <?php foreach($feedbackValues as $value => $label):
			                        $selected= (!empty($selectedFeedBackFields) && $selectedFeedBackFields == $value) ? ' selected' : '';
			                    ?>
			                    <option value="<?php echo $value?>" <?php echo $selected;?>><?php echo $label['value']?></option>
			                    <?php endforeach;?>
			                    <?php if(!empty($this->settings['feedback']['enable_feedback_freetext'])):
			                        $selected= (empty($feedbackValues[$selectedFeedBackFields]) && $selectedFeedBackFields != '') ? ' selected' : '';
			                    ?>
			                    <option value="freetext" <?php echo $selected;?>><?php echo $this->__('Other'); ?></option>
			                    <?php endif;?>
			                </select>
			            </div>
			            <?php if(!empty($this->settings['feedback']['enable_feedback_freetext'])):?>
			                <script type="text/javascript">
			                    $('id_feedback').observe('change', function (event){
			                        if(this.getValue() == 'freetext'){
			                            $('id_feedback_freetext_div').show();
			                        } else {
			                            $('id_feedback_freetext_div').hide();
			                        }
			                    });
			                </script>
			                <div id='id_feedback_freetext_div' class="onestepcheckout-feedback-freetext"<?php echo ((!empty($selectedFeedBackFields) && $selectedFeedBackFields == 'freetext') ? '' : ' style="display: none;"'); ?>>
			                    <label for="id_feedback_freetext"><?php echo $this->__('Please specify:'); ?></label>
			                    <textarea id="id_feedback_freetext" name="onestepcheckout-feedback-freetext"><?php echo $this->getRequest()->getPost('onestepcheckout-feedback-freetext', false);?></textarea>
			                </div>
			            <?php endif; ?>
			        <?php endif; ?>
			        <?php
			        /**
			         * Feedbackdropdown end
			         */
			        ?>
			
			        <?php if($this->settings['enable_terms']): //deprecated?>
			            <div class="onestepcheckout-enable-terms">
			                <?php
			
			                if(isset($this->formErrors['terms_error']) && $this->formErrors['terms_error']) {
			                    $terms_error = true;
			                }
			                else    {
			                    if($_SERVER['REQUEST_METHOD'] == 'POST')    {
			                        $terms_error = false;
			                    }
			                    else    {
			                        $terms_error = true;
			                    }
			                }
			                ?>
			
			                <input class="required-entry" type="checkbox" id="id_accept_terms" name="accept_terms" value="1" <?php if(!$terms_error) echo "checked=\"checked\""; ?> />
			                <label for="id_accept_terms"><?php echo $this->__('I accept the <a id="onestepcheckout-toc-link" target="_blank" href="javascript:void(0);">Terms and Conditions</a>'); ?></label>
			
			                <?php if(isset($this->formErrors['terms_error']) && $this->formErrors['terms_error']): ?>
			                <div class="onestepcheckout-error onestepcheckout-terms-error">
			                    <?php echo $this->__('You must accept our terms to continue.'); ?>
			                </div>
			                <?php endif; ?>
			
			            </div>
			        <?php endif; ?>
			
			        <?php
			        /**
			         * Default magento agreements
			         */
			        ?>
			        <?php if($this->settings['enable_default_terms']): ?>
			            <?php if(!empty($this->formErrors['agreements_error'])):?>
			            <div class="onestepcheckout-error onestepcheckout-terms-error">
			                <?php echo $this->__('Please agree to all the terms and conditions before placing the order.'); ?>
			            </div>
			            <?php endif;?>
			            <?php echo $this->getChildHtml('agreements') ?>
			            <script type="text/javascript">
			                    var termsmodals = new Object;
			                    <?php if($this->settings['enable_textarea']):?>
			                        $$('div.agreement-content').each(
			                                function(element){
			                                    element.id = 'agreement-div-' + element.up('li').down('input').id;
			                                    $$('body')[0].insert(element);
			                                });
			                    <?php endif;?>
			
			                    $$('.checkout-agreements li p input').each(
			                        function(elem){
			                            elem.addClassName('required-entry');
			                            <?php if($this->settings['enable_textarea']):?>
			                            window.termsmodals[elem.id] = new Control.Modal($('agreement-div-' + elem.id),{
			                                overlayOpacity: 0.75,
			                                className: 'modal',
			                                fade: true,
			                                closeOnClick: true,
			                                height: 400,
			                                width: 700
			                            });
			                            <?php endif;?>
			                        }
			                    );
			                    <?php if($this->settings['enable_textarea']):?>
			                    $$('.checkout-agreements li p label').each(
			                        function(elem){
			                            elem.up().insert('<a href="javascript:void(0);" onclick="termsmodals[\'' + elem.htmlFor + '\'].open();">' + elem.innerHTML + '</a>');
			                            elem.hide();
			                        }
			                    );
			                    <?php endif;?>
			            </script>
			        <?php endif;?>
			        <?php
			        /**
			         * Default magento agreements end
			         */
			        ?>
			    </div><br />
				
			    <div class="checkout section last place-holder">
			    	<div class="onestepcheckout-place-order-wrapper">
			        	<button type="button" title="<?php echo $this->__('Place order now'); ?>" id="onestepcheckout-place-order" class="large orange onestepcheckout-button onestepcheckout-place-order" onclick="javasctipt:void(0);"><span><span><?php echo $this->__('Place order now'); ?></span></span></button>
			        </div>
				</div>
			    
			</div>
		</div>
	</fieldset>

</form>

<?php if(!$this->isCustomerLoggedIn() && $helper->showLoginLink()): ?>
    <?php echo $this->getChildHtml('login-popup'); ?>
<?php endif; ?>

<?php if($helper->isValidateEmail()): ?>
<script>
$('billing:email').observe('blur', function(e)    {
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/check_email', array('_secure'=>true)); ?>';
    var email = e.element().getValue();
    var parameters = { email: email };

    new Ajax.Request(url, {
        parameters: parameters,
        onComplete: function(response)  {
            if(response.status == 200)  {
                var result = response.responseText.evalJSON().result;
                if(result == 'invalid') {
                    $('onestepcheckout-email-error-message').update('<?php echo $this->__('Invalid email address.'); ?>');
                    $('onestepcheckout-email-error').show();
                }
                else if(result == 'exists') {
                    <?php if($this->settings['registration_order_without_password']): ?>
                    // Remove the password fields if the email exists in database
                    $('onestepcheckout-li-password').hide();
                    <?php else: ?>

                    $('onestepcheckout-email-error-message').update('<?php echo $this->__('Email address already registered. Please <a href="javascript:void(0);" onclick="login_popup.show(); return false;">login now</a> or use a different email address.'); ?>');
                    $('onestepcheckout-email-error').show();
                    // Ask the user to login or change email address
                    //login_popup.show();
                    $('id_onestepcheckout_username').value = email;
                    <?php endif; ?>
                }
                else    {
                    $('onestepcheckout-email-error').hide();
                    $('onestepcheckout-li-password').show();
                }
            }
        }
    })

});
Validation.add('validate-email', '<?php echo $this->__('This is a required field.') ?>', function(v) {
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/check_email', array('_secure'=>true)); ?>';
    var email = v;
    var parameters = { email: email };
    var value = Validation.get('IsEmpty').test(v) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(v)

    new Ajax.Request(url, {
        parameters: parameters,
        asynchronous: false,
        onComplete: function(response)  {
            if(response.status == 200)  {
                var result = response.responseText.evalJSON().result;
                if(result == 'invalid') {
                    value =  false;
                } else if(result == 'exists') {
                    <?php if($this->settings['registration_order_without_password']): ?>
                    $('onestepcheckout-li-password').hide();
                    <?php else: ?>
                    $('onestepcheckout-email-error-message').update('<?php echo $this->__('Email address already registered. Please <a href="javascript:void(0);" onclick="login_popup.show(); return false;">login now</a> or use a different email address.'); ?>');
                    $('onestepcheckout-email-error').show();
                    $('id_onestepcheckout_username').value = email;
                    value =  false;
                    <?php endif; ?>
                }
            }
        }
    })
    return value;
});
</script>
<?php endif; ?>





<?php if($this->settings['enable_terms']): ?>
<div id="onestepcheckout-toc-popup" style="display: none;">

    <div class="onestepcheckout-popup-wrapper">
        <div class="onestepcheckout-popup-wrapper-inner">
            <h1><?php echo $this->settings['terms_title']; ?></h1>

            <div class="onestepcheckout-toc-terms">
                <?php echo $this->settings['terms_contents']; ?>
            </div>

            <p class="close"><a href="javascript:void(0);"><?php echo $this->__('Close'); ?></a></p>
        </div>
    </div>
    <div class="onestepcheckout-popup-footer">&nbsp;</div>
</div>
<script>
Event.observe(window, 'load', function() {

    var termsPopup = new Control.Modal($('onestepcheckout-toc-popup'), {
        overlayOpacity: 0.65,
        fade: true,
        fadeDuration: 0.3
    });

    $('onestepcheckout-toc-link').observe('click', function(e) {
        e.preventDefault();
        termsPopup.open();
    });

    $$('div#onestepcheckout-toc-popup p.close a').invoke('observe', 'click', function(e) {
        e.preventDefault();
        termsPopup.close();
    });

});

/*
var popup;
Event.observe(window, 'load', function() {
    popup = new OneStepCheckout_Popup('onestepcheckout-toc-popup','onestepcheckout-toc-link', 'div#onestepcheckout-toc-popup p.close a');
});
*/
</script>
<?php endif; ?>





<script>
<?php if($this->hasFormErrors()): ?>
if($$('div.input-error').length > 0) {
    var input = $$('div.input-error')[0].select('input');
    if(input.length == 1)   {
        input[0].focus();
    }
}
<?php endif; ?>
</script>

<?php if(!$this->settings['exclude_region']): ?>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<script type="text/javascript">
//<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');

    <?php if($this->settings['enable_different_shipping'] && !$this->isVirtual()): ?>
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
    <?php endif; ?>
//]]>
</script>
<?php endif; ?>


<script type="text/javascript">

Event.observe(window, 'load', function() {
    if ($$('div.shopping-cart-totals').length == 1) {
    }
    else    {

        var already_placing_order = false;
        var review = false;

        /* Handle place order click event */
        $$('.onestepcheckout-place-order').each(function(elem){
            elem.observe('click', function(e)   {
                Event.stop(e);
				
				
					
               // First validate the form
                var form = new VarienForm('onestepcheckout-form');

                if(!form.validator.validate())  {
                    Event.stop(e);
                } else {

                  if(!already_placing_order && $$('.loading-ajax').length <= 0 ) {
                    <?php if(!empty($helper->settings['addressreview']['enable_addressreview'])):?>
                        var addressTemplates = {
                            shipping: '<?php echo str_replace("\r", '', str_replace("\n", '', $helper->settings['addressreview']['shipping_template']));?>',
                            billing: '<?php echo str_replace("\r", '', str_replace("\n", '', $helper->settings['addressreview']['billing_template']));?>'
                        };
                        addressPreview(addressTemplates, 'addressreview');
                        if(!review){
                            review = true;
                            reviewmodal.container = $('addressreview');
                            reviewmodal.open();
                            reviewmodal.observe('beforeClose',function(){
                                review = false;
                            });
                            return true;
                            Event.stop(e);
                        } else {
                            reviewmodal.close();
                        }
                    <?php endif;?>
					
					
                        already_placing_order = true;

                        var submitelement = $('onestepcheckout-place-order');

                        var loaderelement = new Element('div').
                            addClassName('onestepcheckout-place-order-loading').
                            update('<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>" />&nbsp;&nbsp;<?php echo $this->__('Please wait, processing your order...'); ?>');

                        submitelement.parentNode.appendChild(loaderelement);

                        /* Disable button to avoid multiple clicks */
                        submitelement.removeClassName('orange').addClassName('grey');
                        submitelement.disabled = true;

                        /* Submit the form */
						
						// Ajax Call for the place order click
				
						var url = '/custom/placeorder.php';
						var track_id = <?php echo Mage::getSingleton('core/session')->getCheckouttrackid()?>;
						var parameters = {
							checkouttrackid : track_id
						}
						
						new Ajax.Request(url, {
							method: 'post',
							parameters: parameters,
							onSuccess: function(transport)  {
								 $('onestepcheckout-form').submit();
							}
						});				
						
				// End Ajax Call	
						
                       
                    }
                }
            });
        });


        // This is a separate page
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
        var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

        $$('dl.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
        $$('div.payment-methods input[name="payment\[method\]"]').invoke('observe', 'click', get_separate_save_methods_function(url));

        $$('div.payment-methods input[name="payment\[method\]"]').invoke('observe', 'click', function() {
            $$('div.onestepcheckout-payment-method-error').each(function(item) {
                new Effect.Fade(item);
            });
        });

        $$('dl.shipment-methods input').invoke('observe', 'click', function() {
            $$('div.onestepcheckout-shipment-method-error').each(function(item) {
                new Effect.Fade(item);
            });
        });

        var has_hidden_terms = false;

        if($('id_accept_terms') != null)    {

            $('id_accept_terms').observe('click', function(e)   {
                var element = e.element();

                if(element.checked) {
                    $$('div.onestepcheckout-terms-error').each(function(item) {
                        new Effect.Fade(item);
                        has_hidden_terms = true;
                    });
                }
                else    {
                    if(has_hidden_terms)    {
                        $$('div.onestepcheckout-terms-error').each(function(item) {
                            new Effect.Appear(item);
                            has_hidden_terms = false;
                        });
                    }
                }
            });
        }
    }

    var form = $('onestepcheckout-form');

    /* Highlight selected payment method if one set */
    if($RF(form, 'payment[method]') != null)    {
        try {
            var payment_method = $RF(form, 'payment[method]');
            $('container_payment_method_' + payment_method).show();
            $('payment_form_' + payment_method).show();
        } catch(err)    {

        }
    }

    /* Set default shipping method if not set */
    if($RF(form, 'shipping_method') == null)    {
        try {
            var method = '<?php echo $this->_getDefaultShippingMethod(); ?>';
            if(method != '')    {
                $('s_method_' + method).checked = true;
                get_separate_save_methods_function(url);
            }
        } catch(err)    {

        }
    }

   get_separate_save_methods_function(url);

<?php if($this->differentShippingAvailable()): ?>
    $('billing:use_for_shipping_yes').observe('click', function(e)  {
        var element = e.element();
        if(element.checked){
            $('shipping_address').hide();
			$('shippingmsg').show()
        } else {
			$('shippingmsg').hide()
            if($('shipping-address-select') && $('shipping-address-select').value == ''){
                $('shipping_address_list').show()
            }
            $('shipping_address').show();
            <?php if(!$this->isCustomerLoggedIn()):?>
            $('shipping_address_list').show()
            <?php endif;?>
            <?php if($this->isCustomerLoggedIn()):?>
            if(!$('shipping-address-select') && $('shipping_address_list').getStyle('display')=='none'){
                $('shipping_address_list').show()
            }
            <?php endif;?>
        }

        <?php if($this->settings['enable_ajax_save_billing']): ?>
        get_save_billing_function('<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>', '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>', <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>)();
        <?php endif; ?>

    });
    <?php endif; ?>

    <?php if($this->settings['enable_ajax_save_billing']): ?>

    var url_save_billing = '<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>';
    var url_set_methods = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
    var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;
    var update_on_initial = false;

    var shipping_address_select = $('shipping-address-select');
    var billing_address_select = $('billing-address-select');
    var euvat = $('euvat_action_validate_taxvat');

    if(euvat !== null){
        euvat.observe('click', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
    }
    var billing_region_id = $('billing:region_id');
    var shipping_region_id = $('shipping:region_id');

    <?php if($this->hasAjaxSaveBillingField('country')): ?>

        $('billing:country_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));

        <?php if($this->differentShippingAvailable()): ?>
        $('shipping:country_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods, update_payments));
            <?php if($this->isCustomerLoggedIn()): ?>
            if(shipping_address_select !== null) {
                Event.stopObserving('shipping-address-select', 'change');
                $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            }
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        if(billing_address_select !== null) {
            Event.stopObserving('billing-address-select', 'change');
            $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        }
        <?php endif; ?>
    <?php endif; ?>


    <?php if($this->hasAjaxSaveBillingField('state/region')): ?>
    if(billing_region_id != null){
        $('billing:region_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        $('billing:region').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
    }

        <?php if($this->differentShippingAvailable()): ?>
        if(shipping_region_id != null){
            $('shipping:region_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            $('shipping:region').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        }
            <?php if($this->isCustomerLoggedIn()): ?>
            if(shipping_address_select !== null) {
                Event.stopObserving('shipping-address-select', 'change');
                $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            }
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        if(billing_address_select !== null) {
            Event.stopObserving('billing-address-select', 'change');
            $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        }
        <?php endif; ?>

    <?php endif; ?>



    <?php if($this->hasAjaxSaveBillingField('postcode')): ?>
    $('billing:postcode').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));

        <?php if($this->differentShippingAvailable()): ?>
        $('shipping:postcode').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            <?php if($this->isCustomerLoggedIn()): ?>
            if(shipping_address_select !== null) {
                Event.stopObserving('shipping-address-select', 'change');
                $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            }
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        if(billing_address_select !== null) {
            Event.stopObserving('billing-address-select', 'change');
            $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        }
        <?php endif; ?>

    <?php endif; ?>

    <?php if($this->hasAjaxSaveBillingField('city')): ?>
    $('billing:city').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));

        <?php if($this->differentShippingAvailable()): ?>
        $('shipping:city').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            <?php if($this->isCustomerLoggedIn()): ?>
            if(shipping_address_select !== null) {
                Event.stopObserving('shipping-address-select', 'change');
                $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            }
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        if(billing_address_select !== null) {
            Event.stopObserving('billing-address-select', 'change');
            $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        }
        <?php endif; ?>

    <?php endif; ?>


    <?php endif; ?>

});

if($('payment-tool-tip-close')){
    Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
}

if($('payment-tool-tip-curacao-close')){
    Event.observe($('payment-tool-tip-curacao-close'), 'click', toggleToolTipCuracao);
}


$$('.cvv-what-is-this-curacao').each(function(element){
	Event.observe(element, 'click', toggleToolTipCuracao);
});
function toggleToolTipCuracao(event){
	if($('payment-tool-tip-curacao')){
		$('payment-tool-tip-curacao').setStyle({
			left: (Event.pointerX(event)-300)+'px',
			top: (Event.pointerY(event)-300)+'px'
		});
		$('payment-tool-tip-curacao').toggle();
	}
	Event.stop(event);
} 


</script>
<?php endif; ?>
<div id="onestepcheckout_popup_overlay" style="display: none;">&nbsp;</div>
<div id="loading-process" style="display: none;"></div>
<script type="text/javascript">
	jQuery(function($) {
		
		if(jQuery('.payment_method').is(':checked')) {
			jQuery("#curacao_credit").prop('checked', false);
		 }
		 
		 jQuery('.payment_method').click(function(){
			jQuery("#curacao_credit").prop('checked', false);
		})
		
  });
  
  function usebillingadd(id){
	jQuery("#billingAddress").html('<p>'+jQuery("#billingAdd"+id).html()+'</p>')
	jQuery("#shippingAdd").html('<p>'+jQuery("#billingAdd"+id).html()+'</p>')
	jQuery("#billingAddId").val(id);
	tb_remove();
	jQuery('.checkforshipping').attr('checked', true);
	jQuery('.checkforshipping').val('1');
	return false;
}

function useshippingadd(id){
	jQuery("#shippingAdd").html('<p>'+jQuery("#shipping"+id).html()+'</p>')
	jQuery("#shippingAdd_id").val(id);
	tb_remove();
	jQuery('.checkforshipping').attr('checked', false);
	jQuery('.checkforshipping').val('0');
	
	return false;
}

function removebillingadd(id){
	jQuery.ajax({
			type: "POST",
			url: "/onestepcheckout/ajax/delete/",
			data: {
				id:id
			},
			success: function (data) {
				 
				 var result = jQuery.parseJSON(data); 
				 if(result.success){
					jQuery("#shipping"+id).remove() 
					jQuery("#billingAdd"+id).remove()
					jQuery("#shippingadd"+id).remove()
					jQuery("#shippingremove"+id).remove()
					jQuery("#billingadd"+id).remove()
					jQuery("#billingremove"+id).remove()					
				}
				//alert(data)
				//tb_remove();
				return false;
	
			}
		});
		
		
	return false;	
}

  function customshippingadd(){
	  var err = 0;
	  var err_msg = '';
	  
	  if(jQuery('input[name="shipping[firstname]"]').val()==''){
			err ++;
			err_msg += "Please provide First name\n\r"
		}
		if(jQuery('input[name="shipping[lastname]"]').val()==''){
			err ++;
			err_msg += "Please provide Last name\n\r"
		}
		if(jQuery('#shipping_street1').val()==''){
			err ++;
			err_msg += "Please provide Address\n\r"
		}
		if(jQuery('input[name="shipping[city]"]').val()==''){
			err ++;
			err_msg += "Please provide City\n\r"
		}
		if(jQuery('select[name="shipping[region_id]"]').val()==''){
			err ++;
			err_msg += "Please Choose your state\n\r"
		}
		if(jQuery('input[name="shipping[postcode]"]').val()==''){
			err ++;
			err_msg += "Please provide Zip Code\n\r"
		}
		if(jQuery('input[name="shipping[telephone]"]').val()==''){
			err ++;
			err_msg += "Please provide Telephone Number\n\r"
		}
		if(err>0){
			alert(err_msg)
			return false;
		}
	
	jQuery("#shippingAdd_fname").val(jQuery('input[name="shipping[firstname]"]').val())
	jQuery("#shippingAdd_lname").val(jQuery('input[name="shipping[lastname]"]').val())
	jQuery("#shippingAdd_region_id").val(jQuery('select[name="shipping[region_id]"]').val())
	jQuery("#shippingAdd_city").val(jQuery('input[name="shipping[city]"]').val())
	jQuery("#shippingAdd_country_id").val(jQuery('select[name="shipping[country_id]"]').val())
	jQuery("#shippingAdd_street1").val(jQuery("#shipping_street1").val())
	jQuery("#shippingAdd_street2").val(jQuery("#shipping_street2").val())
	jQuery("#shippingAdd_postcode").val(jQuery('input[name="shipping[postcode]"]').val())
	jQuery("#shippingAdd_telephone").val(jQuery('input[name="shipping[telephone]"]').val())	
	
	
	
	 
		
	var html = '<div>';
	var hidden = ' <input name="shipping[firstname]" type="hidden" value="'+jQuery('input[name="shipping[firstname]"]').val()+'" id="shippingAdd_fname" />'
        hidden += '<input name="shipping[lastname]" type="hidden" value="'+jQuery('input[name="shipping[lastname]"]').val()+'" id="shippingAdd_lname" />'
        hidden += '<input name="shipping[telephone]" type="hidden" value="'+jQuery('input[name="shipping[telephone]"]').val()+'" id="shippingAdd_telephone" />'
        hidden += '<input name="shipping[street][]" type="hidden" value="'+jQuery("#shipping_street1").val()+'" id="shippingAdd_street1" />'
        hidden += '<input name="shipping[street][]" type="hidden" value="'+jQuery("#shipping_street2").val()+'" id="shippingAdd_street2" />'
        hidden += '<input name="shipping[country_id]" type="hidden" value="'+jQuery('select[name="shipping[country_id]"]').val()+'" id="shippingAdd_country_id" />'
        hidden += '<input name="shipping[city]" type="hidden" value="'+jQuery('input[name="shipping[city]"]').val()+'" id="shippingAdd_city" />'
        hidden += '<input name="shipping[region_id]" type="hidden" value="'+jQuery('select[name="shipping[region_id]"]').val()+'" id="shippingAdd_region_id" />'
        hidden += '<input name="shipping[postcode]" type="hidden" value="'+jQuery('input[name="shipping[postcode]"]').val()+'" id="shippingAdd_postcode" />'
       // hidden += '<input type="checkbox" class="checkbox" id="shipping:save_in_address_book" title="Save in address book" value="1" name="shipping[save_in_address_book]" checked="checked"><br />';
	jQuery("#newshippingAdd").html(hidden);
	jQuery("#newshippingAdd").show();	
	 var state;
	 var c;
	 jQuery.get('../custom/getregion.php?region_id='+jQuery("#shippingAdd_region_id").val(), function(data) {
	    state = data
		
		html += jQuery("#shippingAdd_fname").val()+' '+ jQuery("#shippingAdd_lname").val()+'</div><div>';
		html += jQuery("#shippingAdd_street1").val()+' '+jQuery("#shippingAdd_street2").val()+'</div><div>';
		html += jQuery("#shippingAdd_city").val()+' '+state+' '+jQuery("#shippingAdd_postcode").val()+'</div><div>'  
	
		html += jQuery("#shippingAdd_telephone").val()+'</div>';
	    jQuery("#shippingAdd").html('<p>'+html+'</p>')
	    jQuery("#shippingAdd_id").val(' ');
		
		jQuery('.checkforshipping').attr('checked', false);
		jQuery('.checkforshipping').val('0');
		jQuery('#shipping_address').remove();
	    tb_remove();

	}); 
	
	jQuery.ajax({
			type: "POST",
			url: "/onestepcheckout/ajax/addshippingaddress/",
			data: {
				fname: jQuery('input[name="shipping[firstname]"]').val(), lname:jQuery('input[name="shipping[lastname]"]').val() , street1:jQuery("#shipping_street1").val() , street2:jQuery("#shipping_street2").val(), city:jQuery('input[name="shipping[city]"]').val() , state_id:jQuery('select[name="shipping[region_id]"]').val() ,  zip:jQuery('input[name="shipping[postcode]"]').val() , country:jQuery('select[name="shipping[country_id]"]').val() , tel:jQuery('input[name="shipping[telephone]"]').val()
			},
			success: function (data) {
				
				//alert(data)
				
				var result = jQuery.parseJSON(data); 
				 if(result.success){
					jQuery("#shippingaddleft").append('<div id="shipping'+result.address_id+'">'+html+'</div><a id="shippingadd'+result.address_id+'" onclick="return useshippingadd(\''+result.address_id+'\')" href="">Use This Address</a><a id="shippingremove'+result.address_id+'" onclick="return removebillingadd(\''+result.address_id+'\')" href="">Remove</a>')
					
					jQuery("#billingaddleft").append('<div id="billingAdd'+result.address_id+'">'+html+'</div><a id="shippingadd'+result.address_id+'" onclick="return usebillingadd(\''+result.address_id+'\')" href="">Use This Address</a><a id="shippingremove'+result.address_id+'" onclick="return removebillingadd(\''+result.address_id+'\')" href="">Remove</a>')
				}
				
				return false;
	
			}
		});
	

  }
 function custombillingadd(){
	 
	  var err = 0;
	  var err_msg = '';
	 // var state = '';
	  
	  if(jQuery('input[name="billing[firstname]"]').val()==''){
			err ++;
			err_msg += "Please provide First name\n\r"
		}
		if(jQuery('input[name="billing[lastname]"]').val()==''){
			err ++;
			err_msg += "Please provide Last name\n\r"
		}
		if(jQuery('#billing_street1').val()==''){
			err ++;
			err_msg += "Please provide Address\n\r"
		}
		if(jQuery('input[name="billing[city]"]').val()==''){
			err ++;
			err_msg += "Please provide City\n\r"
		}
		if(jQuery('select[name="billing[region_id]"]').val()==''){
			err ++;
			err_msg += "Please Choose your state\n\r"
		}
		if(jQuery('input[name="billing[postcode]"]').val()==''){
			err ++;
			err_msg += "Please provide Zip Code\n\r"
		}
		if(jQuery('input[name="billing[telephone]"]').val()==''){
			err ++;
			err_msg += "Please provide Telephone Number\n\r"
		}
		if(err>0){
			alert(err_msg)
			return false;
		}
	 
 
	 var html = '<div>';	
	var state; 
	 var hiddenfields = '<input name="billing[firstname]" type="hidden" value="'+jQuery('input[name="billing[firstname]"]').val()+'" id="billing:firstname" />'
		hiddenfields += '<input name="billing[lastname]" type="hidden" value="'+jQuery('input[name="billing[lastname]"]').val()+'" id="billing:lastname" />'
		hiddenfields +='<input name="billing[telephone]" type="hidden" value="'+jQuery('input[name="billing[telephone]"]').val()+'" id="billing:telephone" />'
		hiddenfields +='<input name="billing[street1]" type="hidden" value="'+jQuery("#billing_street1").val()+'" id="billing:street1" />'
		hiddenfields +='<input name="billing[street2]" type="hidden" value="'+jQuery("#billing_street2").val()+'" id="billing:street2" />'
		hiddenfields +='<input name="billing[country_id]" type="hidden" value="'+jQuery('select[name="billing[country_id]"]').val()+'" id="billing:country_id" />'
		hiddenfields +='<input name="billing[city]" type="hidden" value="'+jQuery('input[name="billing[city]"]').val()+'" id="billing:city" />'
		hiddenfields +='<input name="billing[region_id]" type="hidden" value="'+jQuery('select[name="billing[region_id]"]').val()+'" id="billing:region_id" />'
		hiddenfields +='<input name="billing[postcode]" type="hidden" value="'+jQuery('input[name="billing[postcode]"]').val()+'" id="billing:postcode" />'
		//hiddenfields += '<input type="checkbox" class="checkbox" id="billing:save_in_address_book" title="Save in address book" value="1" name="billing[save_in_address_book]" checked="true"> Save in the Address Book<br>'
	//alert(jQuery('input[name="billing[street][][0]"]').val());
	
	//hiddenfields
	
	jQuery.get('../custom/getregion.php?region_id='+jQuery('select[name="billing[region_id]"]').val(), function(data) {
		state = data;	
		
		html += jQuery('input[name="billing[firstname]"]').val()+' '+ jQuery('input[name="billing[lastname]"]').val()+'</div><div>';
		html += jQuery("#billing_street1").val()+' '+jQuery("#billing_street2").val()+'</div><div>';
		html += jQuery('input[name="billing[city]"]').val()+' '+state+' '+jQuery('input[name="billing[postcode]"]').val()+'</div><div>'  
	
		html += jQuery('input[name="billing[telephone]"]').val()+'</div>';
	    
		jQuery("#billingAddress").html('<p>'+html+'</p>'+hiddenfields)
	    jQuery("#billingAddId").val(' ');
		
		jQuery("#shippingAdd").html('<p>'+html+'</p>')
	    jQuery("#shippingAdd_id").val(' ');
		
		jQuery('.checkforshipping').attr('checked', true);
		jQuery('.checkforshipping').val('1');
		jQuery('#shipping_address').remove();
	    tb_remove();
		
	});
	
	 jQuery.ajax({
			type: "POST",
			url: "/onestepcheckout/ajax/addaddress/",
			data: {
				fname: jQuery('input[name="billing[firstname]"]').val(), lname:jQuery('input[name="billing[lastname]"]').val() , street1:jQuery("#billing_street1").val() , street2:jQuery("#billing_street2").val(), city:jQuery('input[name="billing[city]"]').val() , state_id:jQuery('select[name="billing[region_id]"]').val() ,  zip:jQuery('input[name="billing[postcode]"]').val() , country:jQuery('select[name="billing[country_id]"]').val() , tel:jQuery('input[name="billing[telephone]"]').val()
			},
			success: function (data) {
				var result = jQuery.parseJSON(data); 
				 if(result.success){
					//window.location = '/onestepcheckout/';
				jQuery("#shippingaddleft").append('<div id="shipping'+result.address_id+'">'+html+'</div><a id="shippingadd'+result.address_id+'" onclick="return useshippingadd(\''+result.address_id+'\')" href="">Use This Address</a><a id="shippingremove'+result.address_id+'" onclick="return removebillingadd(\''+result.address_id+'\')" href="">Remove</a>')
					
					jQuery("#billingaddleft").append('<div id="billingAdd'+result.address_id+'">'+html+'</div><a id="billingadd'+result.address_id+'" onclick="return usebillingadd(\''+result.address_id+'\')" href="">Use This Address</a><a id="billingremove'+result.address_id+'" onclick="return removebillingadd(\''+result.address_id+'\')" href="">Remove</a>')
					
				}
				
				return false;
	
			}
		});
	
	
	
	return false;
	} 


jQuery(document).ready(function() {
	  //wireUpEvents();  
	  jQuery("input[type=radio]").bind("click", function() {
			//alert("here")
			var formdata = jQuery('form').serializeArray();
			 //alert(formdata.toSource());<br />
			jQuery.ajax({
			        type: "POST",
			        url: "../custom/checkouttrack.php",
			        data: formdata,
			        success: function (data) {
			        
			        }
			    })
	
	  });
	  
 
	  
	  jQuery("input[type=text]").bind("change", function() {
			//alert("here")
			var formdata = jQuery('form').serializeArray();
			 //alert(formdata.toSource());<br />
			jQuery.ajax({
			        type: "POST",
			        url: "../custom/checkouttrack.php",
			        data: formdata,
			        success: function (data) {

			            //jQuery("#appId").val(data);
			        }
			    })
	
	  });
	  
	  
	  jQuery("button").bind("click", function() {
			//alert("here")
			var formdata = jQuery('form').serializeArray();
			 //alert(formdata.toSource());<br />
			jQuery.ajax({
			        type: "POST",
			        url: "../custom/checkouttrack.php",
			        data: formdata,
			        success: function (data) {

			            //jQuery("#appId").val(data);
			        }
			    })
	
	  });
	  
	});
	


	/*jQuery(document).scroll(function(){
		var scroll_top = jQuery(document).scrollTop();
		var _top = jQuery('.checkout-left').height() - jQuery('.checkout-right').height();
			
		if(scroll_top < _top) {
			jQuery('.checkout-right').css({'position':'fixed', 'top':'auto'});
		} else {

			jQuery('.checkout-right').css({'position':'absolute', 'top':_top+'px'});
		}
	});

	jQuery('.checkout-left').resize(function() {
		var scroll_top = jQuery(document).scrollTop();
		var _top = jQuery('.checkout-left').height() - jQuery('.checkout-right').height();
			
		if(scroll_top < _top) {
			jQuery('.checkout-right').css({'position':'fixed', 'top':'auto'});
		} else {
			jQuery('.checkout-right').css({'position':'absolute', 'top':_top+'px'});
		}		
	})
*/
</script>

<?php
	mysql_close($link);
?>