<?php
	$_product = $this->getProduct();
	$_helper = $this->helper('catalog/output');
	$_zoomConfig = Mage::getStoreConfig('zoom/general');
?>
<div id="imageShowcase">

	<div class="product-image-zoom">
<?php 
	if ($_product->getImage() != 'no_selection' && $_product->getImage()): 
  	
		$_img = '<a href="'.$this->helper('catalog/image')->init($_product, 'image').'" class="jqzoom" title="" id="anchorproductImgDefault"><img border="0" id="productImgDefault" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(400,392).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'"/></a>';
	  	echo $_helper->productAttribute($_product, $_img, 'image');
  	
	else:
 
        	$_img = '<a href="'.$this->helper('catalog/image')->init($_product, 'image').'" class="jqzoom"><img border="0" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(380).'" alt="'.$this->htmlEscape($_product->getImageLabel()).'" id="productImgDefault"/></a>';
        	echo $_helper->productAttribute($_product, $_img, 'image');
    
	endif;
	
	 if (count($this->getGalleryImages()) > 0): 
	 	$i = 0;
		foreach ($this->getGalleryImages() as $_image):
		
			// Find out image name from image URL
	
			$img_name =  ExtractImageName($this->helper('catalog/image')->init($this->getProduct(), 'image',$_image->getFile()));
			$img_name = $i;
			$_img = '<a href="'.$this->helper('catalog/image')->init($this->getProduct(), 'image',$_image->getFile()).'" id="anchorproductImg'.$img_name.'"><img border="0" id="productImg'.$i.'" src="'.$this->helper('catalog/image')->init($this->getProduct(), 'image',$_image->getFile())->resize(400,392).'" alt="'.$this->htmlEscape($_image->getLabel()).'" title="'.$this->htmlEscape($_image->getLabel()).'"/></a>';  
		
			echo $_helper->productAttribute($this->getProduct(), $_img, 'image');
			
			$i++;
		endforeach; 
	 endif; 
	
?>
  
    </div>
</div>

<?php if (count($this->getGalleryImages()) > 1): ?>

<div class="more-views seven columns alpha omega">
    <ul>
	<?php
		$i = 0;
		
	    foreach ($this->getGalleryImages() as $_image): 
			
			$moreImg = ExtractImageName($this->helper('catalog/image')->init($this->getProduct(), 'image',$_image->getFile()));
			
	    ?>
		<li>
			<img border="0" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(60); ?>" onclick="switchmore('<?php echo $i;?>');" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />		
		</li>
    <?php
    		$i++;    
	    endforeach;
	?>
    </ul>
</div>

<?php endif; ?>

<?php

	function ExtractImageName($fullImagePath)
	{
		$img_extract = explode("/",$fullImagePath);
		$img_len = count($img_extract);
		$fullImgName = $img_extract[$img_len-1]; // Image name from full path
		//$fullImgName_extract = explode(".",$fullImgName);
		//$ImgName = $fullImgName_extract[0];
		$imgName = $fullImgName;
		return $ImgName;
	}

?>
<script type="text/javascript">

       	 jQuery(document).ready(function(){


            var options = {
                zoomWidth: 600,
                zoomHeight: 484,
                showEffect: 'fast',
                hideEffect: 'fadeout',
                fadeoutSpeed: 'fast',
                title: false,
                zoomtype:'innerzoom',
                showPreload: false,
                yOffset: 10
            }
            
            if(!jQuery('body').hasClass('quickshop-index-view'))
	            jQuery(".jqzoom").jqzoom(options);

        });

</script>
<script type="text/javascript">
		// show main image
          jQuery(document).ready(function() {

            // On document ready hide all images first
            jQuery("#imageShowcase img").hide();
            jQuery("#productImgDefault").show();
				
        });
</script>
